### PR TITLE
FakeDevice_refactor

### PR DESCRIPTION
**Pull request by mofii**
This PR mutes, refactors, and ultimately disbles the tests for the FakeDevice

### CODE REVIEW

**Review by stevenaleung — CHANGES_REQUESTED** [review]
`test/emulate/test_fake_device.jl` is still breaking the unit testing workflow. I think either more refactoring is needed to fix the workflow or these tests should be removed altogether since they're not really testing anything (the local server simply prints out the messages that it receives)

**Comment by mofii** [comment]
> `test/emulate/test_fake_device.jl` is still breaking the unit testing workflow. I think either more refactoring is needed to fix the workflow or these tests should be removed altogether since they're not really testing anything (the local server simply prints out the messages that it receives)

Yup, the FakeDevice tests should be disabled - I meant to include commit 1705e052b [https://github.com/Orchard-Ultrasound-Innovation/TcpInstruments.jl/pull/88/commits/1705e052b3240d7b7fb1e8989680430ea6266629] in this PR but that slipped.

Not only do they currently break the unit tests but they also don't run and test the live code that TcpInstruments exposes to the user. So I don't currently see the value of these tests.

The questions becomes what to do with these files after the tests have been disabled. Can we use them to look at when making better tests in the future?

I'd like to merge in this refactor and then we afterwards decide if we delete the code altogether or if we refactor based on this PR.

**Comment by mofii** [comment]
test/emulate/test_fake_device.jl no longer breaks the unit tests

**Review by stevenaleung — APPROVED** [review]
Nice fix!

**Comment by mofii** [comment]
This PR has gotten too old

**Pull request closed without merging**
