### PR TITLE
Update CI to run Julia 1.7

### PR DESCRIPTION
**Pull request by mofii**

### CODE REVIEW

**Comment by stevenaleung** [comment]
If we update this package to Julia 1.7 we should also update all upstream and downstream packages to 1.7. Let's find a date to do the coordinated updating

**Comment by mofii** [comment]
I agree that all packages should be updated to test on 1.7, but what's the motivation for doing a synchronized update?

**Comment by stevenaleung** [comment]
By doing a synchronized update, we'd know right away if any part of the workflow is not compatible with 1.7. If there are problems I think it'd be easier for rolling back

**Comment by stevenaleung** [comment]
Ready to go after adding Julia 1.6 back into github actions

**Comment by mofii** [comment]
Approved?

**Review by stevenaleung — APPROVED** [review]
Approved!

**Pull request merged**
