### PR TITLE
LAB-229-create-tcp-info-wrapper

### PR DESCRIPTION
**Pull request by YoniEisipsSNN**
Addresses the desired change of storing all Tcp communication info in a single struct

### CODE REVIEW

**Comment by YoniEisipsSNN** [comment]
As this was built off of the changes for LAB-228 (pr #197), that branch is set as the base branch for now. However, we can change the base to instrument_type_refactor after merging LAB-228.

**Comment by mofii** [comment]
@YoniEisipsSNN or @gita135 I'll review this PR when it has been rebased to only show the new commits.

**Review by mofii — CHANGES_REQUESTED** [review]
I've put in a significant amount of work to rebase this branch, LB-230 and `instrument_type_refactor`. 

This review started before I carried out the rebasing, I hope all of the comments still make sense.

Besides the comments within, please convert this into a real PR (instead of a draft) and make the unit tests pass as well.
Thanks!

**Comment by mofii** [comment]
Screen Shot 2023-01-10 at 11 00 55
@YoniEisipsSNN a small request, I'd love it if when re-requesting my review, you would do so by clicking the circular arrows icon.

**Review by mofii — APPROVED** [review]
Yes!
Let's get this in!
👍

**Pull request merged**
