### PR TITLE
HWS-181: Add docstrings

### PR DESCRIPTION
**Pull request by gita135**
Added docstrings to all exported functions in ```TcpInstruments.jl ```and reformatted existing docstrings to comply with blue style guide
Addresses issue #144

### CODE REVIEW

**Comment by mofii** [comment]
Hi @gita135, 
Would you mind rebasing this branch (`git rebase -i`) and squashing all related commits?
For instance, squashing all commits after each other starting with "Added arguments.." into one commit.

**Comment by gita135** [comment]
> Hi @gita135, Would you mind rebasing this branch (`git rebase -i`) and squashing all related commits? For instance, squashing all commits after each other starting with "Added arguments.." into one commit.

Wait so just 1 giant commit? Each commit corresponds to adding and/fixing docstring formatting for a specific function

**Comment by mofii** [comment]
No not one giant commit. It would be great if the 139 commits could be compressed into 10-15 commits of similar type commits.
For instance, these 5 commits are so related that they would become 1 commit:
```
Added docstirngs for AgilentB2910BL and Keysight33612A
Added docstrings for SRSPS310 and AgilentE36312A
Added docstrings for AgilentDSOX4034A and AgilentDSOX4024A
Added docstring for KeysightDMM34465A
Added docstrings for Agilent4294A and Agilent4395A
```
Whereas `Fixed indentations` is obviously very different.

I haven't spend the time on reading all the code changes to see which way it would make most sense to combine them. I hope you'll see a common pattern that could be used to segment them.

**Comment by gita135** [comment]
> No not one giant commit. It would be great if the 139 commits could be compressed into 10-15 commits of similar type commits. For instance, these 5 commits are so related that they would become 1 commit:
> 
> ```
> Added docstirngs for AgilentB2910BL and Keysight33612A
> Added docstrings for SRSPS310 and AgilentE36312A
> Added docstrings for AgilentDSOX4034A and AgilentDSOX4024A
> Added docstring for KeysightDMM34465A
> Added docstrings for Agilent4294A and Agilent4395A
> ```
> 
> Whereas `Fixed indentations` is obviously very different.
> 
> I haven't spend the time on reading all the code changes to see which way it would make most sense to combine them. I hope you'll see a common pattern that could be used to segment them.

ok done! squashed them into 17 commits.

**Review by mofii — CHANGES_REQUESTED** [review]
There are a couple of unresolved merge conflicts (or at least headers left over from merge conflicts):
```
~/local_src/TcpInstruments.jl/src (add_docstrings*) » grep -rn  ">>" .                            mf@mortenMBP
./power_supply/types.jl:53:>>>>>>> changes for types.jl
./waveform_generator/types.jl:105:>>>>>>> changes for types.jl
---------------------------------------------------------------------------------------------------------------
~/local_src/TcpInstruments.jl/src (add_docstrings*) » grep -rn  "<<" .                            mf@mortenMBP
./power_supply/types.jl:34:<<<<<<< HEAD
./waveform_generator/types.jl:59:<<<<<<< HEAD
./impedance_analyzer/types.jl:48:<<<<<<< HEAD
./oscilloscope/types.jl:37:<<<<<<< HEAD
---------------------------------------------------------------------------------------------------------------
~/local_src/TcpInstruments.jl/src (add_docstrings*) »
```

**Review by mofii — APPROVED** [review]
👍

**Pull request merged**
