### PR TITLE
Timeout-test

### PR DESCRIPTION
**Pull request by mofii**
This moves the timeout functionality to it's own function.

We're seeing bugs with the timeout functionality. I'd like us to write a set of serious unit tests to test these functions and choose the best implementation.

### CODE REVIEW

**Comment by gita135** [comment]
Oh no, accidently added all prev commmits. only meant to push my 1 commit that fixed the functionality in ```timeout2()``` to replicate ```timeout1()``` behavior

**Comment by mofii** [comment]
Happy New Year's @gita135 !
Can I get you to rebase this branch on the main branch? For inspiration of how to easily do this, you could see the thread on Zulip.

**Comment by gita135** [comment]
> Happy New Year's @gita135 ! Can I get you to rebase this branch on the main branch? For inspiration of how to easily do this, you could see the thread on Zulip.

will do 👍

**Comment by mofii** [comment]
As this PR already seems to be solving a bug (#191) I'm merging it into main. 
We can then base the PRs for timeout() unit tests and a fix for timeout2 on the main branch.

**Pull request merged**
