### PR TITLE
HWS-187: To enable better save() dispatching make sure all existing get_data() functions return a struct

### PR DESCRIPTION
**Pull request by gita135**
Created ```struct instrument name_info ```and ```struct instrument name_data``` and ```get_data(instrument)``` for multimeter, powersupply, SMU and waveform generator

``get_data(instrument)``` since we do not have the instruments here

### CODE REVIEW

**Comment by mofii** [comment]
@gita135 What's the status of this PR?
Are you adapting it based on our Zulip conversation or are you now working in a different branch?

**Comment by gita135** [comment]
> @gita135 What's the status of this PR? Are you adapting it based on our Zulip conversation or are you now working in a different branch?

Adapting based on Zulip convo

**Review by mofii — CHANGES_REQUESTED** [review]
Hi @gita135 ,
I'm sorry to say that most of the work in this PR isn't what I was looking for.
The title is to "make sure all existing get_data() functions.." but you are adding `get_data()` functions not just updating / checking up on existing `get_data()` functions.

The `get_data()` functions are relevant for instruments that we use to record data, such as the oscilloscope and impedance analyzer. You can argue the same for the digital multimeter, but there the returned data is changing depending on the setup - are we for instance measuring temperature with a thermo couple, or, voltage output from a two-port electronic circuit - making it hard to define a static struct to contain that data and dispatch on. 
Maybe we can make things easier/better for the DMM and SMU cases, but it's non-trivial and requires their own discussions. 

For this task / PR, I'd like to make sure that we have a correct save function implementation and dispatching for the existing `get_data()` functions, which I think boils down to two implementations, one for the oscilloscope and one for the impedance analyzer.

**Comment by YoniEisipsSNN** [comment]
I have addressed your concerns with a new pull request #183 if you'd like to check that out

**Comment by mofii** [comment]
closing 😢

**Pull request closed without merging**
